---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: en
  label: English - Pages
  create: all
  match: "*"
- type: directory
  path: en/_posts
  label: English - Posts
  create: all
  match: "**/*"
- type: directory
  path: es
  label: Español - Pages
  create: all
  match: "*"
- type: directory
  path: es/_posts
  label: Español - Posts
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
